### ISSUE TITLE
packeges 

### ISSUE THREAD

**Issue by nouhailahanbali** [baydim/cashier#1]
Running "flutter pub get" in cashier-master...                     17,6s
The plugins `keyboard_visibility, qrscan` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
exit code 0
anyone had the some warning ?

**Comment by baydim** [comment]
hello first i say thanks to you...anyw in this project i use flutter which is not null safety or flutter 2.7.0...if you want it fixed you can delete the plugin version behind.

example:
plugins: ^any

**Comment by nouhailahanbali** [comment]
hi thank you for ansewring my question i tried this solution but still not working i tried to remove
keyboard_visibility plugin and keep    flutter_keyboard_visibility: ^5.3.0
 but i get errors inside codes i changed the import statements but still some of the methods won't work for the flutter keyboard visibility . 
i want to khnow does the app have the feature to add new product if yes yes i want to know wish file .and thank you

**Comment by baydim** [comment]
oh isee function add new product in file controller/barangcontroller.dart on fuction addbarang.....im so thx for your interaction in my repo...hf fun code ✌🏽

**Comment by Raihanadstya** [comment]
hi, I had the problem that when I build this app I get errors "Execution failed for task ':permission_handler:compileDebugJavaWithJavac', how do i solve this problem ? i've already tried to update the compileSdkversion to 31 and still get error

**Comment by baydim** [comment]
solved
